// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaSeEoRuyX2AqTBYFw8fhIEJ_MmEgy6Kk',
    appId: '1:1091000562900:web:7ff44f9ed809022e76f741',
    messagingSenderId: '1091000562900',
    projectId: 'student-management-syste-8209c',
    authDomain: 'student-management-syste-8209c.firebaseapp.com',
    storageBucket: 'student-management-syste-8209c.firebasestorage.app',
    measurementId: 'G-024FHT2JN7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDNVOgFLiMySK_x-oAo-GPBWstn1Bxl_k',
    appId: '1:1091000562900:android:f7fab5e6abef948076f741',
    messagingSenderId: '1091000562900',
    projectId: 'student-management-syste-8209c',
    storageBucket: 'student-management-syste-8209c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtQMReCgNbmralZU-zaWx2Z55-s4YXom4',
    appId: '1:1091000562900:ios:bff07da9552c778276f741',
    messagingSenderId: '1091000562900',
    projectId: 'student-management-syste-8209c',
    storageBucket: 'student-management-syste-8209c.firebasestorage.app',
    iosBundleId: 'com.example.studentManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtQMReCgNbmralZU-zaWx2Z55-s4YXom4',
    appId: '1:1091000562900:ios:bff07da9552c778276f741',
    messagingSenderId: '1091000562900',
    projectId: 'student-management-syste-8209c',
    storageBucket: 'student-management-syste-8209c.firebasestorage.app',
    iosBundleId: 'com.example.studentManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaSeEoRuyX2AqTBYFw8fhIEJ_MmEgy6Kk',
    appId: '1:1091000562900:web:ec97c337ba729b1876f741',
    messagingSenderId: '1091000562900',
    projectId: 'student-management-syste-8209c',
    authDomain: 'student-management-syste-8209c.firebaseapp.com',
    storageBucket: 'student-management-syste-8209c.firebasestorage.app',
    measurementId: 'G-6XKP91ETTT',
  );
}
